[build]
  # Build settings
  publish = "."
  command = "echo 'No build step required'"

[build.environment]
  # Disable secrets scanning for this build
  SECRETS_SCAN_ENABLED = "false"

[functions]
  # Function configuration
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."verify-payment"]
  # Payment verification function timeout
  timeout = 15

[functions."callback"]
  # Webhook callback function timeout  
  timeout = 30

[[headers]]
  # CORS headers for functions
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  # Redirect for payment success with parameters
  from = "/payment-success"
  to = "/payment-success.html"
  status = 200

[[redirects]]
  # Handle function routes
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
